@baseUrl = http://js-post-api.herokuapp.com/api

# Student

# @name getAllStudents
GET {{baseUrl}}/students?_paga=1&limit=10

###
# @name getStudentById
GET {{baseUrl}}/students/1a90afd3-af05-42a5-88d5-a297d387f164

###
# @name addNewStudent
POST {{baseUrl}}/students
Content-Type: application/json

{
  "name": "Michale Test",
  "age": 23,
  "mark": 9,
  "gender": "Male",
  "city": "hcm"
}

###
# @name updateStudent
PATCH {{baseUrl}}/students/1a90afd3-af05-42a5-88d5-a297d387f164
Content-Type: application/json

{
  "name": "Michale Test",
  "age": 23,
  "mark": 9.9,
  "gender": "Male",
  "city": "hn"
}

###
# @name removeStudent
PATCH {{baseUrl}}/students/1a90afd3-af05-42a5-88d5-a297d387f164